name: CI

on:
  push:
    branches: [ mainline ]
  pull_request:
    branches: [ mainline ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1

      - name: JDK environment
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: "adopt"

      - name: Build
        uses: gradle/gradle-build-action@v2
        id: build
        with:
          arguments: build --scan

      - name: Publish
        uses: gradle/gradle-build-action@v3
        id: publish
        with:
          arguments: publish --scan
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.ORG_GRADLE_PROJECT_OSSRHUSERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.ORG_GRADLE_PROJECT_OSSRHPASSWORD }}