name: Build Workflow

on:
  workflow_call:

jobs:
  build-workflow:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1

      - name: JDK environment
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: "adopt"

      - name: Build
        uses: gradle/gradle-build-action@v2
        id: build
        with:
          arguments: build --scan